"""Created events and calendars tables with unicode

Revision ID: 08c852a719fa
Revises: 
Create Date: 2020-03-30 00:38:33.465683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c852a719fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('hash', sa.Unicode(length=256), nullable=False),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index(op.f('ix_calendar_hash'), 'calendar', ['hash'], unique=True)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.Column('description', sa.Unicode(length=4096), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('calendar', sa.Unicode(length=256), nullable=True),
    sa.ForeignKeyConstraint(['calendar'], ['calendar.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_index(op.f('ix_calendar_hash'), table_name='calendar')
    op.drop_table('calendar')
    # ### end Alembic commands ###
